//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Stock_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Products()
        {
            this.Tbl_Sales = new HashSet<Tbl_Sales>();
        }
    
        public int pct_ID { get; set; }
        public string pct_name { get; set; }
        public string pct_brand { get; set; }
        public Nullable<short> pct_category { get; set; }
        public Nullable<decimal> pct_price { get; set; }
        public Nullable<byte> pct_stock { get; set; }
    
        public virtual Tbl_Categories Tbl_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sales> Tbl_Sales { get; set; }
    }
}
