//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Stock_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales
    {
        public int sale_ID { get; set; }
        public Nullable<int> sale_product { get; set; }
        public Nullable<int> sale_costumer { get; set; }
        public Nullable<byte> sale_quantity { get; set; }
        public Nullable<decimal> sale_price { get; set; }
    
        public virtual Tbl_Costumers Tbl_Costumers { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
    }
}
